databases:
  - name: businessflow-db
    plan: free
    databaseName: businessflow
    user: businessflow

services:
  - type: web
    name: businessflow-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: businessflow-db
          property: connectionString
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: CORS_ORIGINS
        value: https://businessflow-frontend-xzso.onrender.com

  - type: web
    name: businessflow-frontend
    runtime: docker
    dockerfilePath: ./frontend/Dockerfile
    dockerContext: ./frontend
    plan: free
    envVars:
      - key: VITE_API_URL
        value: https://businessflow-backend-xzso.onrender.com/api/v1
